---
title: "NIMBLE background"
subtitle: "Valencia International Bayesian Analysis Summer School Workshop"
output: html_document
---


# What is NIMBLE?

Numerical Inference for statistical Models using Bayesian and Likelihood Estimation

- A flexible extension of the BUGS and JAGS systems
- A system for using algorithms on hierarchical statistical models
- A system for programming algorithms to be used on hierarchical models
- A partial compiler for math, flow control, and related syntax in R

We have an extensive website (<a href="http://r-nimble.org" target="_blank" style="color: blue">https://r-nimble.org</a>) with fairly comprehensive User Manual, examples, and other information.

# NIMBLE components

* Model language: A new dialect of BUGS/JAGS for specifying models
* A package of algorithms (MCMC, SMC, MCEM)
* Algorithm language: nimbleFunctions, embedded within R for writing algorithms
* Compiler: Generates and compiles C++ from models and algorithms

# Why NIMBLE?

Here are some of the features you can do in NIMBLE that we are most excited about and that distinguish NIMBLE from other software:

- customize your MCMCs, including choosing what parameters to block
- define your own distributions and functions for use in BUGS code
- use a variety of algorithms on your model, including MCMC, sequential Monte Carlo (particle filtering), and MCEM
- write an algorithm in our system for easy dissemination to others, including your own MCMC sampler
- compile mathematical operations in R without needing to know or write C or C++

# Why Not NIMBLE?

* For MCMCs that rely heavily on Gibbs sampling, JAGS may be a bit faster because of more efficient internal implementation of the calculations.
* For certain model structures, Hamiltonian Monte Carlo, such as implemented in Stan, may work better than the default MCMC samplers in NIMBLE.
  - That said, in a number of examples we've tried we've been able to achieve comparable or better performance either out-of-the-box or with some relatively simple modifications to the model or the MCMC samplers.
  - And yet, sometimes customization is time-consuming and requires specialized knowledge.
* NIMBLE can take a long time to build algorithms for models that have tens of thousands or more nodes (though once built, the algorithm run times can be quite good). We anticipate big improvements in future versions of NIMBLE.

# What are my other options? 

* For MCMC:
  1. <a href="http://mcmc-jags.sourceforge.net" target="_blank" style="color: blue">JAGS</a>
  2. <a href="http://mc-stan.org" target="_blank" style="color: blue">Stan</a>
  3. <a href="https://pymcmc.readthedocs.org/en/latest/" target="_blank" style="color: blue">PyMC</a>
* various sequential Monte Carlo packages
  1. <a href="http://kingaa.github.io/pomp" target="_blank" style="color: blue">POMP</a>: Partially-Observed Markov Processes (standalone)
  2. <a href="http://libbi.org" target="_blank" style="color: blue">LibBI</a>: PMCMC and SMC for state-space models (standalone)
  3. <a href="https://biips.github.io/" target="_blank" style="color: blue">BIIPS</a>: Bayesian Inference with Interacting Particle Systems (standalone, but simular to BUGS/JAGS)
  4. <a href="https://cran.r-project.org/web/packages/SMC/index.html" target="_blank" style="color: blue">SMC</a>: Sequential Monte Carlo (R package)
* various tools for a variety of algorithms in R, Python, Matlab, etc.

# Getting help with NIMBLE

* Post to the <a href="https://groups.google.com/forum/#!forum/nimble-users" target="_blank" style="color: blue">NIMBLE user group</a>
* Email the NIMBLE development team at: $\text{\LARGE{nimble.stats@gmail.com}}$
* Follow announcements via the <a href="https://groups.google.com/forum/#!forum/nimble-announce" target="_blank" style="color: blue">NIMBLE announcements list</a>

And you can feel free email me directly ($\text{\LARGE{dbt1@williams.edu}}$) given your participation in this workshop. However I do encourage you to post to the user group as any of the NIMBLE developers or other users can then help you out.

# Participating in NIMBLE

* Email $\text{\LARGE{nimble.stats@gmail.com}}$ if you're interested in participating in the development of NIMBLE. 
* Develop an algorithm using NIMBLE and either share it with us (e.g., by a Git pull request or more informally) or develop an R package that depends on NIMBLE.
* We have funding to bring selected users to Berkeley for intensive collaboration; contact us if you have an interesting use for NIMBLE in mind and want to explore possibilities with us.
