---
title: "NIMBLE principles and philosophy"
subtitle: "Valencia International Bayesian Analysis Summer School Workshop"
output: html_document
---

# Why did we start NIMBLE?

 - Existing systems don't easily allow users to modify an MCMC.
 - Existing model languages like BUGS restrict what users can do.
 - Existing systems are algorithm specific - MCMC systems, SMC systems, etc.
 - Existing systems don't easily allow methodologists to add algorithms.

As a result, researchers fall back to hand-coding their analyses or methods, or they make do with algorithms that don't work well on their problems.

# Big goals

 - provide researchers with more flexibility in working with their models
 - provide methodologists with a platform for sharing their methods
 - enhance reproducibility of analyses and methods

# More specific goals

 - enable use of multiple methods on a given model
 - enable sharing of methods in a context in which the model specification syntax and model manipulation primitives (calculation, simulation, graph structure queries) don't have to be reinvented
 - encourage tweaking of methods by users
 - reduce reimplementation of commonly-used methods
 - more easily enable composition (combination) of methods (e.g., particle MCMC)
 - help bring methods in the methods literature to researchers

# How does NIMBLE do this?

 - You can extend BUGS with your own distributions and functions
 - Algorithms are written in a high-level R-like syntax that is easily understandable
 - We provide a platform for writing a variety of algorithms with model manipulation primitives that don't have to be reinvented and that operate on BUGS-based models
 - We provide a core set of algorithms, in particular a full MCMC engine
     - You can extend our MCMC engine with your own samplers

# Reference

See our <a href="http://www.tandfonline.com/doi/abs/10.1080/10618600.2016.1172487" target="_blank" style="color: blue">Journal of Computational and Graphical Statistics article</a> for more information. 

