#! /usr/local/bin/Rscript
# usage:
# ./make_slides overview
# cd modules; ../make_slides nimble_bugs
# etc.

library(knitr)
library(rmarkdown)

cmdArgs <- commandArgs(trailingOnly = TRUE)

if(length(cmdArgs) == 0) {
    system('make clean')
    cmdArgs <- list.files(pattern = '\\.Rmd$', recursive = TRUE)
}

## remove trailing period (.), if present
cmdArgs <- gsub('\\.$', '', cmdArgs)

## remove trailing (.Rmd), if present
cmdArgs <- gsub('\\.Rmd', '', cmdArgs)

for(f in cmdArgs) {
    filename <- paste0(f, '.Rmd')
    if(!file.exists(filename)) {
        message(paste0('could not find file: ', filename))
        next
    }
    knit(filename, envir = new.env())
    mdFile <- gsub('modules/', '', paste(f, ".md", sep = ""))
    system(paste("pandoc -s --webtex -t slidy ", mdFile, " -o ", paste(f, "_slides.html", sep = ""), " --self-contained"))
    ##system(paste("pandoc -s --webtex -t slidy --variable linkcolor=cyan --variable filecolor=cyan --variable urlcolor=cyan --variable toccolor=cyan --variable citecolor=cyan ", mdFile, " -o ", paste(f, "_slides.html", sep = ""), " --self-contained"))
    ##system(paste("pandoc -s --webtex -t slidy --variable linkcolor=cyan --variable filecolor=cyan --variable urlcolor=cyan --variable toccolor=cyan --variable citecolor=cyan ", mdFile, " -o ", paste(f, "_slides.html", sep = ""), " --self-contained"))
    ##system(paste("pandoc -s --webtex -t slidy --variable links-as-notes ", mdFile, " -o ", paste(f, "_slides.html", sep = ""), " --self-contained"))
    render(filename, envir = new.env()) # for style that can hide code chunks dynamically
    ## purl(source) ## make separate .R file with just the code
    ## knit2html(source, envir = new.env())
}






f <- 'overview'
f <- 'logistics'
f <- 'modules/1.2_bugs_language'

rm -f ${mdfile}.R       ## remove existing .R file, if one exists
/usr/local/bin/Rscript -e

purl('${mdfile}.rmd', documentation = 0)

purl(filename, documentation = 0)

gsed -i "s/^## //" ${mdfile}.R     ## uncomment any R lines (generated from eval = FALSE code blocks)

